[package]
name = "ev3rover"
version = "0.1.0"
authors = ["jeremyw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ev3dev-lang-rust = { git = "https://github.com/pixix4/ev3dev-lang-rust" }
